INSERT INTO USERS VALUES (1,'a','',1,'$2a$10$RogPwRa0/JrnYbwLxLmSIOYkt1T7LRHyykPCSuEljwSnQQvF728eq');
INSERT INTO USERS VALUES (2,'b','',1,'$2a$10$ZsK6gN4rIdBQqCLdC9YTLewLXm3rVScrfnkpq/gzK6Z4/WyiZ8CIi');
INSERT INTO ROLE VALUES (1,'ADMIN');
INSERT INTO ROLE VALUES (2,'USER');
--
INSERT INTO USERS_ROLE VALUES (1,1);
INSERT INTO USERS_ROLE VALUES (2,2);
;